name: "promote semantic-release"
description: "GitHub Action to promote your code to your next release. Promote develop to alpha, alpha to beta, beta to prod, etc."
author: "levibostian"
inputs: # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
  sequence:
    description: "Comma separated string containing the sequence of your releases that you follow for your project. Each item in the sequence is the name of a branch that you use in your project. Example: 'develop,alpha,beta,main'"
    required: true
  promoteToBranch:
    description: "By default, Action will promote existing branch to next branch in sequence. If you want to instead jump directly to a different branch in the sequence, enter it here."
    required: false 
    default: ""
  githubToken:
    description: "GitHub personal access token for a GitHub account that has push access to the repository."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout all branches and commits history for checking out and merging
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        token: ${{ inputs.githubToken }}
    - name: Run promotion script 
      run: node ${{ github.action_path }}/action.js ${{ inputs.sequence }} ${{ inputs.promoteToBranch }}
      shell: bash 

branding:
  icon: 'fast-forward'  
  color: 'purple'