# Yeah, we are using our own action to promote releases!!
name: Promote releases

on: 
  workflow_dispatch: # manually run this Action so you decide when deployments happen
    inputs:
      promoteBranch:
        description: 'What release to promote to?'     
        required: false
        default: ""
        type: choice
        options:
        - alpha
        - beta
        - main

jobs:
  promote-release:
    name: Promote a branch to the next release 
    runs-on: ubuntu-latest # Action is tested with Linux and it's recommended to use Linux. 
    steps:
      - uses: actions/checkout@v2
      - name: Promote release 
        uses: ./ 
        with:
          sequence: "develop,alpha,beta,main"
          githubToken: ${{ secrets.BOT_PUSH_TOKEN }}
          promoteToBranch: ${{ github.event.inputs.promoteBranch }}